[package]
name = "worldchat"
version = "0.1.0"
authors = ["Andrew Wason <rectalogic@rectalogic.com>"]
repository = "https://github.com/rectalogic/worldchat"
edition = "2024"
description = "Chat in a 2D world via IRC"
license = "MIT OR Apache-2.0"
categories = ["game", "graphics", "irc", "chat"]
keywords = ["game", "bevy", "irc", "chat"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-channel = "2.5.0"
bevy = { version = "0.19.0-rc.1", default-features = false, features = ["2d", "ui", "web", "webgl2", "system_clipboard"] }
irc-proto = { version = "1.1.0", default-features = false }
tokio-tungstenite-wasm = { version = "0.8.2", features = ["native-tls"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
serde = { version = "1.0.228", features = ["derive"] }
postcard = { version = "1.1.3", features = ["alloc"] }
base64 = "0.22.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "net"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.64"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
multiple_crate_versions = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
